'use client';

import { useState, useMemo, useCallback } from 'react';
import { useAtlasStore } from '@/lib/store';
import { CATEGORY_COLORS } from '@/lib/types';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Download, Copy, Check, FileText, FileJson, Star, GitFork, ShieldCheck } from 'lucide-react';

interface ExportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function ExportDialog({ open, onOpenChange }: ExportDialogProps) {
  const { projects, username } = useAtlasStore();
  const [format, setFormat] = useState<'markdown' | 'json'>('markdown');
  const [copied, setCopied] = useState(false);

  // Compute stats
  const stats = useMemo(() => {
    const totalRepos = projects.length;
    const totalStars = projects.reduce((s, p) => s + p.stargazersCount, 0);
    const languages = new Set(projects.map(p => p.language).filter(Boolean));
    const categories = new Set(projects.map(p => p.category).filter(Boolean));
    const deepAnalyzed = projects.filter(p => p.deepAnalyzedAt).length;
    return { totalRepos, totalStars, languages: languages.size, categories: categories.size, deepAnalyzed };
  }, [projects]);

  // Framework usage summary
  const frameworkSummary = useMemo(() => {
    const map = new Map<string, number>();
    projects.forEach(p => {
      p.codeSignature?.frameworks?.forEach(fw => {
        map.set(fw, (map.get(fw) || 0) + 1);
      });
    });
    return [...map.entries()].sort((a, b) => b[1] - a[1]);
  }, [projects]);

  // Shared dependencies summary
  const sharedDepsSummary = useMemo(() => {
    const map = new Map<string, number>();
    projects.forEach(p => {
      const allDeps = [...(p.dependencies?.runtime || []), ...(p.dependencies?.dev || [])];
      allDeps.forEach(dep => {
        map.set(dep, (map.get(dep) || 0) + 1);
      });
    });
    return [...map.entries()].filter(([, count]) => count > 1).sort((a, b) => b[1] - a[1]);
  }, [projects]);

  // Get health status
  const getHealthStatus = useCallback((p: typeof projects[0]) => {
    if (p.isArchived) return 'archived';
    if (!p.pushedAt) return 'unknown';
    const daysSincePush = (Date.now() - new Date(p.pushedAt).getTime()) / (1000 * 60 * 60 * 24);
    if (daysSincePush < 30) return 'healthy';
    if (daysSincePush < 180) return 'moderate';
    return 'stale';
  }, []);

  // Generate Markdown
  const markdownContent = useMemo(() => {
    const lines: string[] = [];

    lines.push(`# ${username}'s Project Portfolio`);
    lines.push('');
    lines.push(`> Generated by Git Atlas on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
    lines.push('');

    // Stats header
    lines.push('## Portfolio Overview');
    lines.push('');
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Total Repos | ${stats.totalRepos} |`);
    lines.push(`| Total Stars | ${stats.totalStars} |`);
    lines.push(`| Languages | ${stats.languages} |`);
    lines.push(`| Categories | ${stats.categories} |`);
    lines.push(`| Deep Analyzed | ${stats.deepAnalyzed} |`);
    lines.push('');

    // Project table
    lines.push('## Projects');
    lines.push('');
    lines.push('| # | Name | Language | Category | Stars | Last Active | Health |');
    lines.push('|---|------|----------|----------|-------|-------------|--------|');
    projects.forEach((p, i) => {
      const health = getHealthStatus(p);
      const lastActive = p.pushedAt ? new Date(p.pushedAt).toLocaleDateString() : 'N/A';
      lines.push(`| ${i + 1} | [${p.name}](${p.htmlUrl}) | ${p.language || '-'} | ${p.category || '-'} | ${p.stargazersCount} | ${lastActive} | ${health} |`);
    });
    lines.push('');

    // Per-project details
    lines.push('## Project Details');
    lines.push('');
    projects.forEach(p => {
      const health = getHealthStatus(p);
      const allDeps = [...(p.dependencies?.runtime || []), ...(p.dependencies?.dev || [])];
      lines.push(`### ${p.name}`);
      lines.push('');
      if (p.description) lines.push(`**Description:** ${p.description}`);
      if (p.deepSummary) lines.push(`**Deep Summary:** ${p.deepSummary}`);
      if (p.codeSignature?.frameworks?.length) {
        lines.push(`**Tech Stack:** ${p.codeSignature.frameworks.join(', ')}`);
      }
      if (p.tags.length > 0 || p.topics.length > 0) {
        lines.push(`**Tags:** ${[...p.tags, ...p.topics].join(', ')}`);
      }
      lines.push(`**Dependencies:** ${allDeps.length}`);
      lines.push(`**Health:** ${health}`);
      lines.push(`**URL:** ${p.htmlUrl}`);
      lines.push('');
    });

    // Framework usage
    if (frameworkSummary.length > 0) {
      lines.push('## Framework Usage');
      lines.push('');
      frameworkSummary.forEach(([fw, count]) => {
        lines.push(`- **${fw}**: ${count} project${count > 1 ? 's' : ''}`);
      });
      lines.push('');
    }

    // Shared dependencies
    if (sharedDepsSummary.length > 0) {
      lines.push('## Shared Dependencies');
      lines.push('');
      lines.push('| Dependency | Used In |');
      lines.push('|-----------|---------|');
      sharedDepsSummary.slice(0, 30).forEach(([dep, count]) => {
        lines.push(`| ${dep} | ${count} project${count > 1 ? 's' : ''} |`);
      });
      lines.push('');
    }

    return lines.join('\n');
  }, [username, projects, stats, frameworkSummary, sharedDepsSummary, getHealthStatus]);

  // Generate JSON
  const jsonContent = useMemo(() => {
    const exportData = {
      exportedAt: new Date().toISOString(),
      username,
      stats: {
        totalRepos: stats.totalRepos,
        totalStars: stats.totalStars,
        languages: stats.languages,
        categories: stats.categories,
        deepAnalyzed: stats.deepAnalyzed,
      },
      projects: projects.map(p => ({
        name: p.name,
        fullName: p.fullName,
        description: p.description,
        htmlUrl: p.htmlUrl,
        language: p.language,
        category: p.category,
        stargazersCount: p.stargazersCount,
        forksCount: p.forksCount,
        isArchived: p.isArchived,
        tags: [...p.tags, ...p.topics],
        summary: p.summary,
        deepSummary: p.deepSummary,
        codeSignature: p.codeSignature,
        dependencies: p.dependencies,
        pushedAt: p.pushedAt,
        health: getHealthStatus(p),
      })),
      frameworkSummary: frameworkSummary.map(([fw, count]) => ({ framework: fw, count })),
      sharedDependencies: sharedDepsSummary.map(([dep, count]) => ({ dependency: dep, count })),
    };
    return JSON.stringify(exportData, null, 2);
  }, [username, projects, stats, frameworkSummary, sharedDepsSummary, getHealthStatus]);

  const content = format === 'markdown' ? markdownContent : jsonContent;

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const textarea = document.createElement('textarea');
      textarea.value = content;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [content]);

  const handleDownload = useCallback(() => {
    const ext = format === 'markdown' ? 'md' : 'json';
    const mimeType = format === 'markdown' ? 'text/markdown' : 'application/json';
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${username}-portfolio.${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [content, format, username]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[750px] bg-card/95 backdrop-blur-md border-border/30 max-h-[85vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Download className="w-5 h-5 text-emerald-400" />
            Export Portfolio
          </DialogTitle>
          <DialogDescription>
            Export your project portfolio in Markdown or JSON format
          </DialogDescription>
        </DialogHeader>

        <Tabs value={format} onValueChange={(v) => setFormat(v as 'markdown' | 'json')} className="flex-1 flex flex-col min-h-0">
          <div className="flex items-center justify-between">
            <TabsList className="bg-card/50 border border-border/20">
              <TabsTrigger value="markdown" className="gap-1.5 text-xs data-[state=active]:bg-emerald-600/20 data-[state=active]:text-emerald-400">
                <FileText className="w-3.5 h-3.5" />
                Markdown
              </TabsTrigger>
              <TabsTrigger value="json" className="gap-1.5 text-xs data-[state=active]:bg-emerald-600/20 data-[state=active]:text-emerald-400">
                <FileJson className="w-3.5 h-3.5" />
                JSON
              </TabsTrigger>
            </TabsList>

            {/* Stats pills */}
            <div className="flex items-center gap-2 text-[10px] text-muted-foreground/50">
              <span className="flex items-center gap-1">
                <Star className="w-3 h-3 text-amber-400/50" />
                {stats.totalStars} stars
              </span>
              <span className="flex items-center gap-1">
                <ShieldCheck className="w-3 h-3 text-emerald-400/50" />
                {stats.deepAnalyzed} analyzed
              </span>
              <span className="flex items-center gap-1">
                <GitFork className="w-3 h-3 text-blue-400/50" />
                {stats.totalRepos} repos
              </span>
            </div>
          </div>

          <TabsContent value="markdown" className="flex-1 min-h-0 mt-3">
            <ScrollArea className="h-[50vh] rounded-lg border border-border/20 bg-background/30">
              <pre className="p-4 text-[11px] text-foreground/70 font-mono leading-relaxed whitespace-pre-wrap">
                {markdownContent}
              </pre>
            </ScrollArea>
          </TabsContent>

          <TabsContent value="json" className="flex-1 min-h-0 mt-3">
            <ScrollArea className="h-[50vh] rounded-lg border border-border/20 bg-background/30">
              <pre className="p-4 text-[11px] text-foreground/70 font-mono leading-relaxed whitespace-pre-wrap">
                {jsonContent}
              </pre>
            </ScrollArea>
          </TabsContent>
        </Tabs>

        {/* Action buttons */}
        <div className="flex items-center justify-between pt-2 border-t border-border/10">
          <div className="text-[10px] text-muted-foreground/30">
            {format === 'markdown' ? 'Markdown' : 'JSON'} &middot; {content.length.toLocaleString()} chars
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopy}
              className="h-8 gap-1.5 text-xs border-emerald-500/30 text-emerald-400 hover:bg-emerald-500/10"
            >
              {copied ? (
                <><Check className="w-3.5 h-3.5" /> Copied!</>
              ) : (
                <><Copy className="w-3.5 h-3.5" /> Copy to Clipboard</>
              )}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={handleDownload}
              className="h-8 gap-1.5 text-xs border-amber-500/30 text-amber-400 hover:bg-amber-500/10"
            >
              <Download className="w-3.5 h-3.5" />
              Download .{format === 'markdown' ? 'md' : 'json'}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
